FROM postgres 
# Expose Port
EXPOSE 5432
ENV POSTGRES_USER admin
ENV POSTGRES_PASSWORD admin
ENV POSTGRES_DB ipam 
#COPY ./pg/init.sql /docker-entrypoint-initdb.d/
#COPY pg/*.* ./
#COPY *.* .
#WORKDIR /pg
#COPY . .
#CMD ["mkdir", "-p", "/var/run/docker.sock"]
	  
